### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by joaquimpuig** [lecopivo/SciLean#11]
The documentation refers to an example https://github.com/lecopivo/SciLean/blob/master/examples/HarmonicOscilator.lean which does not refer to any existing webpage.

**Comment by lecopivo** [comment]
I have fixed the link, but the example is broken right now. I'm in the middle of substantial rewrite of core parts of the library. Fortunately, I'm almost done and the example with be functioning again in couple of days.

**Comment by joaquimpuig** [comment]
Dear Tomas,

I am happy to learn that the library is moving on. I think that it is a
good idea.

Best wishes,

Joaquim

El dt., 22 d’ag. 2023, 15:46, Tomáš Skřivan ***@***.***> va
escriure:

**Comment by lecopivo** [comment]
Thank you for the encouragement! 

The HarmonicOscillator.lean example works again, closing the issue
