### ISSUE TITLE
odd interaction with `Id`

### ISSUE THREAD

**Issue by alok** [lecopivo/SciLean#47]
`import SciLean` breaks some of my code, even if I don't use it directly. Unsure why, but here's a diagnostic, where Coe Id' seem to be synthesized a lot

![2024-11-21-02-10-16](https://github.com/user-attachments/assets/429bbc19-7c17-4f72-91f1-98deb10f2009)

**Comment by alok** [comment]
If I change the `*` on line 42 to `.matmul` it works fine though. So something is messing with my hmul instance in scilean 

![2024-11-21-02-12-21](https://github.com/user-attachments/assets/56fe6ab6-dd3a-40f7-a7a6-f3f603d1be59)

**Comment by lecopivo** [comment]
Can you give me mwe?

**Comment by lecopivo** [comment]
I fixed [one instance with `Id'`](https://github.com/lecopivo/SciLean/commit/d43e4f3df99e2a7772355d4163911f3d977f7d42), does that fix your problem?

**Comment by alok** [comment]
I'll try it out and report
